name: zoom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase 
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1

  # DI
  get_it: ^7.2.0

  # State Managment
  flutter_bloc: ^8.1.2
  
  # Utils
  google_sign_in: ^5.2.4
  intl: ^0.17.0
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
